// Koyumé — catalogue + bilingual strings (FR default, EN).
// Brand voice: premium, sober, benefit-first. Core promise: sleep autonomy
// (falls asleep alone, sleeps through the night). Asia = origin of the ritual,
// mentioned once with restraint. No mascot storytelling.
// Shopify: checkout happens on the Shopify store below via cart permalinks;
// each product carries the numeric ID of its Shopify variant.
window.lpmShopifyDomain = 'jv1j5c-7a.myshopify.com';
window.lpmProducts = [
  {
    id: 'petit', img: '../../assets/products/coussin-mouton.jpg', dims: '13 × 30 cm',
    price: '32 €', priceEn: '€32', shopifyVariant: '43175297614033',
    fr: { name: 'Le Petit', age: 'Nouveau-nés · 0–1 an', fabric: 'Velours doux, motif aquarelle', desc: "Le premier oreiller. Format berceau, tout en douceur, pour l’éveil et les câlins — avant 2 ans, il accompagne les journées, pas les nuits. Garnissage hypoallergénique, housse en fibre de bambou lavable." },
    en: { name: 'The Small', age: 'Newborns · 0–1 year', fabric: 'Soft velvet, watercolour print', desc: 'The first pillow. Cradle-sized and gentle, for waking hours and cuddles — before age 2 it belongs to the day, not the night. Hypoallergenic filling, washable bamboo-fibre cover.' },
  },
  {
    id: 'moyen', img: '../../assets/products/coussin-moyen-toile.jpg', dims: '18 × 38 cm', badge: { tone: 'wool', fr: 'Le plus choisi', en: 'Most chosen' },
    price: '42 €', priceEn: '€42', shopifyVariant: '43175297646801',
    fr: { name: 'Le Moyen', age: 'Tout-petits · 1–3 ans', fabric: 'Toile de Jouy « Bergerie »', desc: "Le format des premières grandes nuits. L’oreiller que l’enfant serre pour s’endormir — et pour se rendormir, seul. Garnissage hypoallergénique, housse en fibre de bambou lavable." },
    en: { name: 'The Medium', age: 'Toddlers · 1–3 years', fabric: '“Bergerie” toile de Jouy', desc: 'The size of the first big nights. The pillow a child holds to fall asleep — and to fall back asleep, alone. Hypoallergenic filling, washable bamboo-fibre cover.' },
  },
  {
    id: 'grand', img: '../../assets/products/coussin-mouton.jpg', dims: '23 × 53 cm',
    price: '54 €', priceEn: '€54', shopifyVariant: '43175297679569',
    fr: { name: 'Le Grand', age: 'Enfants · dès 3 ans', fabric: 'Velours doux, motif aquarelle', desc: "Le format des grands. Un repère pour les nuits entières, un appui pour les histoires du soir. Garnissage hypoallergénique, housse en fibre de bambou lavable." },
    en: { name: 'The Large', age: 'Children · 3 years and up', fabric: 'Soft velvet, watercolour print', desc: 'The size for big kids. An anchor for full nights, a companion for bedtime stories. Hypoallergenic filling, washable bamboo-fibre cover.' },
  },
];

window.lpmT = {
  fr: {
    announce: 'Livraison offerte dès 50 €',
    nav: ['Les oreillers', 'Qui sommes-nous'],
    cartLabel: 'Votre panier', langOther: 'EN',
    reassurance: ['Dessiné en France', 'Housse bambou, lavable en machine', 'Garnissage hypoallergénique', '30 nuits d’essai · retours offerts'],
    heroEyebrow: 'Le véritable compagnon de sommeil',
    heroTitle1: 'Le sommeil,', heroTitle2: 'en toute autonomie.',
    heroSub: 'Aux parents qui comptent les réveils : un oreiller que l’enfant serre pour trouver le sommeil — et le retrouver seul, à 3 heures du matin. Sobre, sain, pensé pour durer.',
    heroCta: 'Découvrir les oreillers', heroCta2: 'Choisir sa taille',
    heroCaption: 'Le Moyen — toile de Jouy « Bergerie »',
    heroTitle: 'Le sommeil, en toute autonomie.',
    lifestyleEyebrow: 'Dans leurs chambres', lifestyleTitle: 'Le soir devient simple', lifestyleText: 'Vous connaissez les soirées en pointillés et les réveils de 3 heures. Un rituel court, une présence rassurante — et les soirées redeviennent des soirées.',
    storyEyebrow: 'La maison', storyTitle: 'L’Asie nous a appris une chose : le sommeil s’apprend', storyText: 'Née dans une famille française expatriée en Asie, Koyumé transpose un rituel simple : un oreiller compagnon, une routine brève, des nuits autonomes.',
    storyCta: 'Découvrir la maison',
    collTitle: 'Trois tailles, un rituel',
    collSub: 'Du premier oreiller d’éveil au format des grandes nuits.',
    filmEyebrow: 'En mouvement',
    filmTitle: 'Voyez-les prendre vie',
    nightEyebrow: 'La promesse',
    nightTitle: 'L’autonomie, pas à pas',
    nightValues: [
      ['Le soir', 'Une présence douce au moment d’éteindre. Le rituel se raccourcit, la porte se referme sereinement.'],
      ['La nuit', 'Au réveil de 3 heures, le compagnon est là. L’enfant se rendort par lui-même — sans traverser le couloir.'],
      ['Le matin', 'Une nuit entière, faite seul. La fierté de l’enfant, le repos des parents.'],
      ['En voyage', 'En voiture, en train ou en avion : le compagnon suit, et les longs trajets deviennent des siestes.'],
    ],
    guideTitle: 'Quelle taille pour votre enfant ?',
    guideRows: [['Le Petit', '13 × 30 cm', '0–1 an', 'Le format berceau, tout en douceur'], ['Le Moyen', '18 × 38 cm', '1–3 ans', 'Le plus choisi — premières grandes nuits'], ['Le Grand', '23 × 53 cm', 'dès 3 ans', 'Le format des nuits entières']],
    guideCols: ['Modèle', 'Dimensions', 'Âge', ''],
    clubEyebrow: 'Le club Koyumé',
    clubTitle: 'Restons en contact',
    clubText: 'Nouveautés, petites séries et jolies attentions — directement dans votre boîte mail.',
    clubPlaceholder: 'Votre adresse e-mail', clubCta: 'S’inscrire', clubNote: 'Pas de spam, promis.',
    clubDone: 'Merci ! À très vite.',
    addToCart: 'Ajouter au panier', qty: 'Quantité', size: 'Dimensions', fabricLabel: 'La matière',
    added: 'Ajouté au panier',
    productReassurance: ['Expédié sous 48 h — livraison offerte dès 50 €', 'Housse bambou lavable · garnissage hypoallergénique', '30 nuits d’essai, retours offerts'],
    maison: {
      eyebrow: 'Qui sommes-nous',
      title: 'L’Asie nous a appris une chose : le sommeil s’apprend',
      intro: 'Koyumé est née dans une famille française expatriée en Asie. On y découvre un rituel que l’Europe ignore : très tôt, les enfants s’endorment seuls, blottis contre un oreiller — leur véritable compagnon de sommeil. Nous en avons fait un objet à notre image — épuré, sain, fait pour durer — pensé pour les chambres d’ici.',
      blocks: [
        ['Le rituel', 'Observé chaque soir dans des millions de chambres d’Asie : un oreiller compagnon, une routine brève, des nuits autonomes. Simple, et remarquablement efficace.'],
        ['L’objet', 'Garnissage hypoallergénique, housse en fibre de bambou lavable en machine, coutures faites pour des années de nuits. Dessiné en France.'],
        ['La promesse', 'Des enfants qui s’endorment — et se rendorment — par eux-mêmes. Essayez 30 nuits ; les retours sont offerts.'],
      ],
      quote: '« Le plus beau cadeau à faire à un enfant : la fierté de ses propres nuits. »',
    },
    guideSommeil: {
      eyebrow: 'Le guide du sommeil',
      title: 'Bien dormir, ça s’apprend doucement',
      intro: 'Quelques repères simples pour accompagner le sommeil de votre enfant — sans dogme, sans angoisse.',
      articles: [
        ['Chaque âge a son format', 'Du berceau au grand lit, le bon oreiller est celui qui suit l’enfant : tout doux et discret pour les premiers mois, plus enveloppant quand viennent les histoires du soir. Suivez toujours les recommandations de votre pédiatre.'],
        ['L’endormissement autonome', 'L’oreiller donne à l’enfant un repère stable : le même objet, le même geste, chaque soir. C’est cette constance qui lui apprend à trouver le sommeil sans assistance — et à le retrouver seul la nuit.'],
        ['Le rituel du soir', 'Une heure régulière, une lumière chaude, une histoire. Les enfants dorment mieux dans la répétition — et avec un compagnon qu’ils aiment.'],
        ['L’entretien, sans y penser', 'Housse lavée à 30 °C une fois par mois, garnissage aéré à chaque changement de draps. C’est tout.'],
      ],
      cta: 'Découvrir les trois tailles',
    },
    faq: {
      eyebrow: 'Vos questions',
      title: 'On vous répond',
      intro: 'Les réponses aux questions qu’on nous pose le plus souvent. Il en manque une ? Écrivez-nous, on répond vite.',
      groups: [
        ['Général', [
          ['D’où vient Koyumé ?', 'D’un rituel observé en Asie, où les enfants s’endorment très tôt par eux-mêmes, blottis contre un oreiller compagnon de sommeil — ce que les anglophones appellent un « sleep buddy ». Les nôtres sont dessinés en France ; les matières sont certifiées OEKO-TEX Standard 100.'],
          ['La livraison', 'Expédition sous 48 h depuis nos ateliers. Livraison offerte dès 50 €, en France métropolitaine.'],
          ['Les retours', 'Vous avez 30 nuits pour essayer. Les retours sont offerts — l’oreiller doit simplement nous revenir propre et complet.'],
        ]],
        ['L’oreiller', [
          ['Comment ça marche ?', 'L’oreiller donne à l’enfant un repère stable pour s’endormir sans assistance — et s’y rendormir au réveil nocturne, sans traverser le couloir. Un apprentissage en douceur, observé depuis des générations en Asie. Chaque enfant est unique : d’où les 30 nuits d’essai.'],
          ['Quelle taille choisir ?', 'Le Petit (13 × 30 cm) pour les 0–1 an, Le Moyen (18 × 38 cm) pour les 1–3 ans, Le Grand (23 × 53 cm) dès 3 ans. Le guide du sommeil détaille chaque âge.'],
          ['À partir de quel âge ?', 'Chaque enfant est différent : suivez toujours les recommandations de votre pédiatre, en particulier avant 2 ans où l’oreiller accompagne les moments d’éveil, pas la nuit.'],
          ['En quoi est-il fait, comment l’entretenir ?', 'Garnissage 100 % polyester hypoallergénique ; housse en fibre de bambou, douce et respirante, lavable en machine à 30 °C, séchage à l’air libre. Le garnissage retrouve son gonflant en quelques heures.'],
        ]],
        ['Votre commande', [
          ['Puis-je l’offrir ?', 'Bien sûr. Chaque commande peut partir en emballage cadeau, avec un petit mot manuscrit si vous nous le confiez.'],
          ['Ma commande n’est pas arrivée', 'Écrivez-nous avec votre numéro de commande : nous répondons sous 24 h ouvrées et nous ne vous laissons jamais sans solution.'],
        ]],
      ],
      contact: 'Une autre question ? Écrivez-nous à guillaumev39@gmail.com — nous répondons sous 24 h.',
    },
    back: 'Retour aux oreillers',
    tabs: ['Description', 'Entretien', 'Livraison'],
    care: 'Housse en fibre de bambou, lavable en machine à 30 °C. Garnissage hypoallergénique — séchage à l’air libre, gonflant retrouvé en quelques heures.',
    shipping: 'Expédition sous 48 h. Livraison offerte dès 50 €, retours possibles pendant 30 jours.',
    review: '« Trois semaines qu’elle fait ses nuits. On n’y croyait plus. » — Claire, maman d’Anna, 2 ans',
    cartEmpty: 'Votre panier est vide, pour l’instant.',
    continueShopping: 'Poursuivre la visite', checkout: 'Passer commande',
    subtotal: 'Sous-total', freeShipHint: 'Livraison offerte dès 50 €',
    provisional: 'visuel provisoire',
    footerBaseline: 'Oreillers pour enfants — véritables compagnons de sommeil. Dessinés en France.',
    footerCols: [['La boutique', ['Les oreillers']], ['L’aide', ['Livraison & retours', 'Entretien', 'Nous écrire']], ['À propos', ['Qui sommes-nous']]],
    legal: '© 2026 Koyumé — fait avec soin',
  },
  en: {
    announce: 'Free delivery over €50',
    nav: ['The pillows', 'About us'],
    cartLabel: 'Your bag', langOther: 'FR',
    reassurance: ['Designed in France', 'Bamboo cover, machine washable', 'Hypoallergenic filling', '30-night trial · free returns'],
    heroEyebrow: 'The true sleep companion',
    heroTitle1: 'Independent sleep,', heroTitle2: 'at last.',
    heroSub: 'For parents who count the wake-ups: a pillow a child holds to find sleep — and find it again, alone, at 3 a.m. Sober, healthy, built to last.',
    heroCta: 'Discover the pillows', heroCta2: 'Find the right size',
    heroCaption: 'The Medium — “Bergerie” toile de Jouy',
    heroTitle: 'Independent sleep, at last.',
    lifestyleEyebrow: 'In their bedrooms', lifestyleTitle: 'Evenings become simple', lifestyleText: 'You know the stop-start evenings and the 3 a.m. calls. A short ritual, a reassuring presence — and evenings belong to evenings again.',
    storyEyebrow: 'The house', storyTitle: 'Asia taught us one thing: sleep can be learned', storyText: 'Born in a French family living in Asia, Koyumé carries over a simple ritual: a companion pillow, a brief routine, independent nights.',
    storyCta: 'Discover the house',
    collTitle: 'Three sizes, one ritual',
    collSub: 'From the first daytime pillow to the size of big nights.',
    filmEyebrow: 'In motion',
    filmTitle: 'See them come to life',
    nightEyebrow: 'The promise',
    nightTitle: 'Independence, step by step',
    nightValues: [
      ['The evening', 'A gentle presence at lights-out. The ritual gets shorter; the door closes calmly.'],
      ['The night', 'At the 3 a.m. wake-up, the companion is right there. The child settles back to sleep alone — no trip down the hallway.'],
      ['The morning', 'A full night, done alone. Pride for the child, rest for the parents.'],
      ['On the road', 'Car, train or plane: the companion comes along — and long journeys become naps.'],
    ],
    guideTitle: 'Which size for your child?',
    guideRows: [['The Small', '13 × 30 cm', '0–1 year', 'The cradle size, all softness'], ['The Medium', '18 × 38 cm', '1–3 years', 'Most chosen — the first big nights'], ['The Large', '23 × 53 cm', '3 and up', 'The size of full nights']],
    guideCols: ['Model', 'Dimensions', 'Age', ''],
    clubEyebrow: 'The Koyumé club',
    clubTitle: 'Let’s stay in touch',
    clubText: 'New arrivals, small series and lovely attentions — straight to your inbox.',
    clubPlaceholder: 'Your email address', clubCta: 'Sign up', clubNote: 'No spam, promise.',
    clubDone: 'Thank you! See you soon.',
    addToCart: 'Add to bag', qty: 'Quantity', size: 'Dimensions', fabricLabel: 'The fabric',
    added: 'Added to your bag',
    productReassurance: ['Ships within 48 h — free delivery over €50', 'Washable bamboo cover · hypoallergenic filling', '30-night trial, free returns'],
    maison: {
      eyebrow: 'About us',
      title: 'Asia taught us one thing: sleep can be learned',
      intro: 'Koyumé was born in a French family living in Asia. There, a ritual Europe has never known: very early, children fall asleep on their own, curled against a pillow — their true sleep companion. We made it an object in our own image — understated, healthy, built to last — designed for bedrooms here.',
      blocks: [
        ['The ritual', 'Observed every evening in millions of bedrooms across Asia: one companion pillow, a brief routine, independent nights. Simple, and remarkably effective.'],
        ['The object', 'Hypoallergenic filling, a machine-washable bamboo-fibre cover, seams made for years of nights. Designed in France.'],
        ['The promise', 'Children who fall asleep — and fall back asleep — by themselves. Try it for 30 nights; returns are free.'],
      ],
      quote: '“The finest gift you can give a child: pride in their own nights.”',
    },
    guideSommeil: {
      eyebrow: 'The sleep guide',
      title: 'Sleeping well is learned gently',
      intro: 'A few simple landmarks to accompany your child’s sleep — no dogma, no anxiety.',
      articles: [
        ['Every age has its size', 'From cradle to big bed, the right pillow follows the child: soft and discreet for the first months, more enveloping when bedtime stories begin. Always follow your paediatrician’s advice.'],
        ['Falling asleep independently', 'The pillow gives the child a stable anchor: the same object, the same gesture, every evening. That constancy is what teaches them to find sleep without assistance — and to find it again alone at night.'],
        ['The evening ritual', 'A regular hour, a warm light, a story. Children sleep better in repetition — and with a companion they love.'],
        ['Care, without thinking about it', 'Cover washed at 30 °C once a month, filling aired at every change of sheets. That’s all.'],
      ],
      cta: 'Discover the three sizes',
    },
    faq: {
      eyebrow: 'Your questions',
      title: 'We answer',
      intro: 'Answers to the questions we hear most often. Missing one? Write to us — we reply quickly.',
      groups: [
        ['General', [
          ['Where does Koyumé come from?', 'From a ritual observed across Asia, where children fall asleep on their own from an early age, curled against a companion pillow — sometimes called a “sleep buddy”. Ours are designed in France; materials are OEKO-TEX Standard 100 certified.'],
          ['Delivery', 'Ships within 48 h from our workshops. Free delivery over €50 in mainland France.'],
          ['Returns', 'You have 30 nights to try. Returns are free — the pillow simply needs to come back clean and complete.'],
        ]],
        ['The pillow', [
          ['How does it work?', 'The pillow gives the child a stable anchor to fall asleep without assistance — and to settle back to sleep at night wake-ups, without a trip down the hallway. A gentle learning, observed for generations across Asia. Every child is unique: hence the 30-night trial.'],
          ['Which size should I choose?', 'The Small (13 × 30 cm) for 0–1 year, The Medium (18 × 38 cm) for 1–3 years, The Large (23 × 53 cm) from age 3. The sleep guide details every age.'],
          ['From what age?', 'Every child is different: always follow your paediatrician’s advice — especially before age 2, when the pillow is for waking moments, not the night.'],
          ['What is it made of, and how do I care for it?', '100% hypoallergenic polyester filling; a soft, breathable bamboo-fibre cover, machine-washable at 30 °C, air-dried. The filling regains its loft within hours.'],
        ]],
        ['Your order', [
          ['Can I gift it?', 'Of course. Every order can leave gift-wrapped, with a handwritten note if you share one with us.'],
          ['My order hasn’t arrived', 'Write to us with your order number: we reply within 24 working hours and never leave you without a solution.'],
        ]],
      ],
      contact: 'Another question? Write to us at guillaumev39@gmail.com — we reply within 24 h.',
    },
    back: 'Back to the pillows',
    tabs: ['Description', 'Care', 'Delivery'],
    care: 'Bamboo-fibre cover, machine-washable at 30 °C. Hypoallergenic filling — air-dry; it regains its loft within hours.',
    shipping: 'Ships within 48 h. Free delivery over €50, returns within 30 days.',
    review: '“Three weeks of full nights. We had stopped believing it was possible.” — Claire, mother of Anna, 2',
    cartEmpty: 'Your bag is empty, for now.',
    continueShopping: 'Keep browsing', checkout: 'Checkout',
    subtotal: 'Subtotal', freeShipHint: 'Free delivery over €50',
    provisional: 'provisional visual',
    footerBaseline: 'Children’s pillows — true sleep companions. Designed in France.',
    footerCols: [['The shop', ['The pillows']], ['Help', ['Delivery & returns', 'Care', 'Write to us']], ['About', ['About us']]],
    legal: '© 2026 Koyumé — made with care',
  },
};
