// Les Petits Moutons — catalogue + bilingual strings (FR default, EN).
// Shopify: checkout happens on the Shopify store below via cart permalinks;
// each product carries the numeric ID of its Shopify variant.
window.lpmShopifyDomain = 'jv1j5c-7a.myshopify.com';
window.lpmProducts = [
  {
    id: 'petit', img: '../../assets/products/coussin-mouton.jpg', dims: '30 × 40 cm',
    price: '25 €', priceEn: '€25', shopifyVariant: '43175297614033',
    fr: { name: 'Le Petit', age: '2–4 ans', fabric: 'Velours « Mouton rêveur »', desc: "Le premier oreiller. Un garnissage bas et souple qui soutient la nuque sans la contraindre, un velours doux imprimé à l'aquarelle, et nos fanions de coton à mordiller du bout des doigts." },
    en: { name: 'The Small', age: '2–4 years', fabric: '“Dreaming sheep” velvet', desc: 'The very first pillow. A low, supple filling that supports the neck without constraining it, a soft watercolour-printed velvet, and our little cotton flags to fiddle with.' },
  },
  {
    id: 'moyen', img: '../../assets/products/coussin-moyen-toile.jpg', dims: '40 × 60 cm', badge: { tone: 'wool', fr: 'Le plus choisi', en: 'Most chosen' },
    price: '34 €', priceEn: '€34', shopifyVariant: '43175297646801',
    fr: { name: 'Le Moyen', age: '5–8 ans', fabric: 'Toile de Jouy « Bergerie »', desc: "L'oreiller des grandes nuits. Notre toile de Jouy « Bergerie », tissée en France, habille un garnissage équilibré qui accompagne les épaules qui grandissent." },
    en: { name: 'The Medium', age: '5–8 years', fabric: '“Bergerie” toile de Jouy', desc: 'The pillow for big nights. Our French-woven “Bergerie” toile de Jouy dresses a balanced filling that keeps up with growing shoulders.' },
  },
  {
    id: 'grand', img: '../../assets/detail-toile.png', imgProvisional: true, dims: '50 × 70 cm',
    price: '40 €', priceEn: '€40', shopifyVariant: '43175297679569',
    fr: { name: 'Le Grand', age: '9–12 ans', fabric: 'Toile de Jouy « Bergerie »', desc: "Presque un oreiller de grand — la douceur en plus. Un soutien plus ferme, une housse en lin lavé et toile de Jouy, pour les dernières années de la chambre d'enfant." },
    en: { name: 'The Large', age: '9–12 years', fabric: '“Bergerie” toile de Jouy', desc: 'Almost a grown-up pillow — with the softness kept in. Firmer support and a washed-linen and toile de Jouy cover, for the last years of the children’s bedroom.' },
  },
];

window.lpmT = {
  fr: {
    nav: ['Les oreillers', 'La maison', 'Le guide du sommeil'],
    cartLabel: 'Votre panier', langOther: 'EN',
    reassurance: ['Toile de Jouy tissée en France', 'Coton bio certifié OEKO-TEX', 'Façonné à la main', '30 nuits d’essai · retours offerts'],
    heroEyebrow: 'Maison française · depuis 2026',
    heroTitle: 'De belles nuits, dès ce soir',
    heroSub: 'Trois oreillers, trois âges. Toile de Jouy, coton bio et velours tendre — façonnés dans nos ateliers français.',
    heroCta: 'Découvrir les oreillers', heroCta2: 'Le guide des tailles',
    collTitle: 'Trois tailles, une douceur',
    collSub: 'Un oreiller pensé pour chaque âge, de la première sieste aux grandes nuits.',
    lifestyleEyebrow: 'Dans leurs chambres',
    lifestyleTitle: 'Dessiné pour être le plus beau du lit',
    lifestyleText: 'Notre toile « Bergerie » reprend les codes de la toile de Jouy du XVIIIᵉ — bergers, moutons et clochers — dans une écriture douce qui apaise les soirs.',
    guideTitle: 'Quelle taille pour votre enfant ?',
    guideRows: [['Le Petit', '30 × 40 cm', '2–4 ans', 'Premier oreiller, soutien très souple'], ['Le Moyen', '40 × 60 cm', '5–8 ans', 'Soutien équilibré, le choix des parents'], ['Le Grand', '50 × 70 cm', '9–12 ans', 'Soutien affirmé, presque comme les grands']],
    guideCols: ['Modèle', 'Dimensions', 'Âge', 'Soutien'],
    storyEyebrow: 'La maison',
    storyTitle: 'La toile de Jouy, retissée pour l’enfance',
    storyText: 'Chaque oreiller est coupé, cousu et garni à la main dans nos ateliers. Les matières sont choisies pour durer toutes les années de la chambre d’enfant — et se laver, souvent.',
    storyCta: 'Découvrir la maison',
    addToCart: 'Ajouter au panier', qty: 'Quantité', size: 'Dimensions', fabricLabel: 'La matière',
    added: 'Ajouté au panier',
    productReassurance: ['Expédié sous 48 h — livraison offerte dès 50 €', '30 nuits d’essai, retours offerts', 'Coton bio certifié OEKO-TEX Standard 100'],
    maison: {
      eyebrow: 'La maison',
      title: 'Une maison française, née d’une chambre d’enfant',
      intro: 'Les Petits Moutons est née d’un constat simple : il n’existait pas de bel oreiller pour enfants. Trop mous, trop synthétiques, trop criards. Nous avons voulu un objet juste — sain, durable, et beau dans la chambre.',
      blocks: [
        ['La toile « Bergerie »', 'Notre toile de Jouy est dessinée à la main puis tissée en France. Bergers, moutons et clochers — une scène du XVIIIᵉ revisitée pour l’enfance.'],
        ['Les ateliers', 'Chaque oreiller est coupé, cousu et garni à la main. Les fanions de coton sont posés un à un, comme une signature.'],
        ['La promesse', 'Des matières certifiées, un soutien pensé par âge, et un objet qui traverse toutes les années de la chambre d’enfant.'],
      ],
      quote: '« Un bel objet pour de belles nuits — rien de plus, rien de moins. »',
    },
    guideSommeil: {
      eyebrow: 'Le guide du sommeil',
      title: 'Bien dormir, ça s’apprend doucement',
      intro: 'Quelques repères simples pour accompagner le sommeil de votre enfant — sans dogme, sans angoisse.',
      articles: [
        ['À quel âge le premier oreiller ?', 'Avant 2 ans, pas d’oreiller — c’est la recommandation pédiatrique. Vers 2–3 ans, au passage au grand lit, un oreiller bas et souple comme Le Petit accompagne la transition.'],
        ['Choisir la bonne hauteur', 'Un bon oreiller comble l’espace entre la nuque et le matelas, sans casser l’alignement du dos. Nos trois tailles suivent la croissance — du soutien très souple au soutien affirmé.'],
        ['Le rituel du soir', 'Une heure régulière, une lumière chaude, une histoire. Les enfants dorment mieux dans la répétition — et dans une chambre qu’ils aiment.'],
        ['L’entretien, sans y penser', 'Housse lavée à 30 °C une fois par mois, garnissage aéré à chaque changement de draps. C’est tout.'],
      ],
      cta: 'Découvrir les trois tailles',
    },
    livraison: {
      eyebrow: 'L’aide',
      title: 'Livraison & retours',
      intro: 'Des règles simples et sans surprise — vos nuits méritent mieux que des petites lignes.',
      articles: [
        ['Expédition sous 48 h', 'Chaque commande est préparée à la main dans le Var, puis confiée à Colissimo. Comptez 3 à 5 jours ouvrés pour la France métropolitaine.'],
        ['5,90 € — offerte dès 50 €', 'Livraison Colissimo à domicile à 5,90 €, offerte dès 50 € d’achat. Deux oreillers voyagent très bien ensemble.'],
        ['30 nuits pour essayer', 'Un oreiller s’adopte la nuit. Si celui-ci ne convient pas à votre enfant, vous avez 30 nuits pour nous le dire — retour offert, remboursement intégral.'],
        ['Le retour, pas à pas', 'Écrivez-nous, nous vous envoyons une étiquette de retour prépayée. Collez-la sur le colis, déposez-le dans votre boîte aux lettres ou en bureau de poste — le remboursement part dès réception.'],
      ],
      cta: 'Découvrir les oreillers',
    },
    entretien: {
      eyebrow: 'L’aide',
      title: 'L’entretien',
      intro: 'Pensés pour la vraie vie d’une chambre d’enfant — c’est-à-dire lavés, souvent.',
      articles: [
        ['La housse, en machine', 'Housse déhoussable, lavable en machine à 30 °C, cycle délicat, zip fermé pour protéger la toile et les fanions.'],
        ['Le séchage, à l’air', 'À l’air libre, à plat ou sur un fil, loin des radiateurs. Pas de sèche-linge : la toile de Jouy n’aime pas ça.'],
        ['Le garnissage', 'Aérez l’oreiller à chaque changement de draps — il retrouve son gonflant en quelques heures près d’une fenêtre entrouverte.'],
        ['Les petites taches', 'Un peu de savon de Marseille et d’eau tiède, sans frotter fort. Sur le velours, brossez doucement une fois sec.'],
      ],
      cta: 'Découvrir les oreillers',
    },
    back: 'Retour aux oreillers',
    tabs: ['Description', 'Entretien', 'Livraison'],
    care: 'Housse déhoussable, lavable en machine à 30 °C. Séchage à l’air libre — le garnissage retrouve son gonflant en quelques heures.',
    shipping: 'Expédition sous 48 h. Livraison Colissimo à 5,90 €, offerte dès 50 €. 30 nuits d’essai, retours offerts.',
    review: '« Le Moyen a remplacé trois oreillers achetés en grande surface. On aurait dû commencer par là. » — Claire, maman d’Anna, 6 ans',
    cartEmpty: 'Votre panier est vide, pour l’instant.',
    continueShopping: 'Poursuivre la visite', checkout: 'Passer commande',
    subtotal: 'Sous-total', freeShipHint: 'Livraison offerte dès 50 €',
    provisional: 'visuel provisoire',
    footerBaseline: 'Oreillers pour enfants, façonnés en France.',
    footerCols: [['La boutique', [{ label: 'Les oreillers', to: 'home' }]], ['L’aide', [{ label: 'Livraison & retours', to: 'livraison' }, { label: 'Entretien', to: 'entretien' }, { label: 'Nous écrire', to: 'mailto:guillaumev39@gmail.com' }]], ['La maison', [{ label: 'Notre histoire', to: 'maison' }, { label: 'Le guide du sommeil', to: 'guide' }]]],
    legal: '© 2026 Les Petits Moutons — façonné avec soin en France',
  },
  en: {
    nav: ['The pillows', 'The house', 'The sleep guide'],
    cartLabel: 'Your bag', langOther: 'FR',
    reassurance: ['Toile de Jouy woven in France', 'OEKO-TEX certified organic cotton', 'Hand-finished', '30-night trial · free returns'],
    heroEyebrow: 'French maison · since 2026',
    heroTitle: 'Beautiful nights, starting tonight',
    heroSub: 'Three pillows, three ages. Toile de Jouy, organic cotton and tender velvet — made in our French workshops.',
    heroCta: 'Discover the pillows', heroCta2: 'Size guide',
    collTitle: 'Three sizes, one softness',
    collSub: 'A pillow designed for every age, from first naps to big nights.',
    lifestyleEyebrow: 'In their bedrooms',
    lifestyleTitle: 'Designed to be the prettiest thing on the bed',
    lifestyleText: 'Our “Bergerie” print revisits 18th-century toile de Jouy — shepherds, sheep and steeples — in a gentle hand that soothes the evenings.',
    guideTitle: 'Which size for your child?',
    guideRows: [['The Small', '30 × 40 cm', '2–4 years', 'First pillow, very supple support'], ['The Medium', '40 × 60 cm', '5–8 years', 'Balanced support, the parents’ choice'], ['The Large', '50 × 70 cm', '9–12 years', 'Firmer support, almost grown-up']],
    guideCols: ['Model', 'Dimensions', 'Age', 'Support'],
    storyEyebrow: 'The house',
    storyTitle: 'Toile de Jouy, rewoven for childhood',
    storyText: 'Every pillow is cut, sewn and filled by hand in our workshops. Materials are chosen to last all the years of the children’s bedroom — and to be washed, often.',
    storyCta: 'Discover the house',
    addToCart: 'Add to bag', qty: 'Quantity', size: 'Dimensions', fabricLabel: 'The fabric',
    added: 'Added to your bag',
    productReassurance: ['Ships within 48 h — free delivery over €50', '30-night trial, free returns', 'OEKO-TEX Standard 100 certified organic cotton'],
    maison: {
      eyebrow: 'The house',
      title: 'A French maison, born in a child’s bedroom',
      intro: 'Les Petits Moutons was born of a simple observation: there was no beautiful pillow for children. Too soft, too synthetic, too loud. We wanted a just object — healthy, durable, and beautiful in the room.',
      blocks: [
        ['The “Bergerie” toile', 'Our toile de Jouy is drawn by hand, then woven in France. Shepherds, sheep and steeples — an 18th-century scene revisited for childhood.'],
        ['The workshops', 'Every pillow is cut, sewn and filled by hand. The little cotton flags are set one by one, like a signature.'],
        ['The promise', 'Certified materials, age-specific support, and an object made to last all the years of the children’s bedroom.'],
      ],
      quote: '“A beautiful object for beautiful nights — nothing more, nothing less.”',
    },
    guideSommeil: {
      eyebrow: 'The sleep guide',
      title: 'Sleeping well is learned gently',
      intro: 'A few simple landmarks to accompany your child’s sleep — no dogma, no anxiety.',
      articles: [
        ['At what age, the first pillow?', 'Before age 2, no pillow — that is the paediatric recommendation. Around 2–3, with the move to a big bed, a low and supple pillow like The Small eases the transition.'],
        ['Choosing the right height', 'A good pillow fills the space between neck and mattress without breaking the alignment of the back. Our three sizes follow growth — from very supple to firmer support.'],
        ['The evening ritual', 'A regular hour, a warm light, a story. Children sleep better in repetition — and in a room they love.'],
        ['Care, without thinking about it', 'Cover washed at 30 °C once a month, filling aired at every change of sheets. That’s all.'],
      ],
      cta: 'Discover the three sizes',
    },
    livraison: {
      eyebrow: 'Help',
      title: 'Delivery & returns',
      intro: 'Simple rules, no surprises — your nights deserve better than fine print.',
      articles: [
        ['Ships within 48 h', 'Every order is prepared by hand in the Var, then entrusted to Colissimo. Allow 3 to 5 working days for mainland France.'],
        ['€5.90 — free over €50', 'Colissimo home delivery at €5.90, free from €50. Two pillows travel very well together.'],
        ['30 nights to try', 'A pillow is adopted at night. If this one does not suit your child, you have 30 nights to tell us — free return, full refund.'],
        ['Returning, step by step', 'Write to us and we will send you a prepaid return label. Stick it on the parcel, drop it in your letterbox or at a post office — the refund is issued on reception.'],
      ],
      cta: 'Discover the pillows',
    },
    entretien: {
      eyebrow: 'Help',
      title: 'Care',
      intro: 'Designed for the real life of a child’s bedroom — that is, washed often.',
      articles: [
        ['The cover, in the machine', 'Removable cover, machine-washable at 30 °C on a delicate cycle, zip closed to protect the toile and the little flags.'],
        ['Drying, in the air', 'Air-dry, flat or on a line, away from radiators. No tumble dryer: toile de Jouy does not like it.'],
        ['The filling', 'Air the pillow at every change of sheets — it regains its loft within hours near an open window.'],
        ['Small stains', 'A little Marseille soap and lukewarm water, without rubbing hard. On velvet, brush gently once dry.'],
      ],
      cta: 'Discover the pillows',
    },
    back: 'Back to the pillows',
    tabs: ['Description', 'Care', 'Delivery'],
    care: 'Removable cover, machine-washable at 30 °C. Air-dry — the filling regains its loft within hours.',
    shipping: 'Ships within 48 h. Colissimo delivery €5.90, free over €50. 30-night trial, free returns.',
    review: '“The Medium replaced three supermarket pillows. We should have started here.” — Claire, mother of Anna, 6',
    cartEmpty: 'Your bag is empty, for now.',
    continueShopping: 'Keep browsing', checkout: 'Checkout',
    subtotal: 'Subtotal', freeShipHint: 'Free delivery over €50',
    provisional: 'provisional visual',
    footerBaseline: 'Children’s pillows, made in France.',
    footerCols: [['The shop', [{ label: 'The pillows', to: 'home' }]], ['Help', [{ label: 'Delivery & returns', to: 'livraison' }, { label: 'Care', to: 'entretien' }, { label: 'Write to us', to: 'mailto:guillaumev39@gmail.com' }]], ['The house', [{ label: 'Our story', to: 'maison' }, { label: 'The sleep guide', to: 'guide' }]]],
    legal: '© 2026 Les Petits Moutons — made with care in France',
  },
};
