// Les Petits Moutons — catalogue + bilingual strings (FR default, EN).
window.lpmProducts = [
  {
    id: 'petit', img: '../../assets/products/coussin-mouton.jpg', dims: '30 × 40 cm',
    price: '25 €', priceEn: '€25',
    fr: { name: 'Le Petit', age: '2–4 ans', fabric: 'Velours « Mouton rêveur »', desc: "Le premier oreiller. Un garnissage bas et souple qui soutient la nuque sans la contraindre, un velours doux imprimé à l'aquarelle, et nos fanions de coton à mordiller du bout des doigts." },
    en: { name: 'The Small', age: '2–4 years', fabric: '“Dreaming sheep” velvet', desc: 'The very first pillow. A low, supple filling that supports the neck without constraining it, a soft watercolour-printed velvet, and our little cotton flags to fiddle with.' },
  },
  {
    id: 'moyen', img: '../../assets/products/coussin-moyen-toile.jpg', dims: '40 × 60 cm', badge: { tone: 'wool', fr: 'Le plus choisi', en: 'Most chosen' },
    price: '34 €', priceEn: '€34',
    fr: { name: 'Le Moyen', age: '5–8 ans', fabric: 'Toile de Jouy « Bergerie »', desc: "L'oreiller des grandes nuits. Notre toile de Jouy « Bergerie », tissée en France, habille un garnissage équilibré qui accompagne les épaules qui grandissent." },
    en: { name: 'The Medium', age: '5–8 years', fabric: '“Bergerie” toile de Jouy', desc: 'The pillow for big nights. Our French-woven “Bergerie” toile de Jouy dresses a balanced filling that keeps up with growing shoulders.' },
  },
  {
    id: 'grand', img: '../../assets/detail-toile.png', imgProvisional: true, dims: '50 × 70 cm',
    price: '40 €', priceEn: '€40',
    fr: { name: 'Le Grand', age: '9–12 ans', fabric: 'Toile de Jouy « Bergerie »', desc: "Presque un oreiller de grand — la douceur en plus. Un soutien plus ferme, une housse en lin lavé et toile de Jouy, pour les dernières années de la chambre d'enfant." },
    en: { name: 'The Large', age: '9–12 years', fabric: '“Bergerie” toile de Jouy', desc: 'Almost a grown-up pillow — with the softness kept in. Firmer support and a washed-linen and toile de Jouy cover, for the last years of the children\u2019s bedroom.' },
  },
];

window.lpmT = {
  fr: {
    nav: ['Les oreillers', 'La maison', 'Le guide du sommeil'],
    cartLabel: 'Votre panier', langOther: 'EN',
    reassurance: ['Toile de Jouy tissée en France', 'Coton bio certifié OEKO-TEX', 'Façonné à la main', '30 nuits d’essai · retours offerts'],
    heroEyebrow: 'Maison française · depuis 2026',
    heroTitle: 'De belles nuits, dès ce soir',
    heroSub: 'Trois oreillers, trois âges. Toile de Jouy, coton bio et velours tendre — façonnés dans nos ateliers français.',
    heroCta: 'Découvrir les oreillers', heroCta2: 'Le guide des tailles',
    collTitle: 'Trois tailles, une douceur',
    collSub: 'Un oreiller pensé pour chaque âge, de la première sieste aux grandes nuits.',
    lifestyleEyebrow: 'Dans leurs chambres',
    lifestyleTitle: 'Dessiné pour être le plus beau du lit',
    lifestyleText: 'Notre toile « Bergerie » reprend les codes de la toile de Jouy du XVIIIᵉ — bergers, moutons et clochers — dans une écriture douce qui apaise les soirs.',
    guideTitle: 'Quelle taille pour votre enfant ?',
    guideRows: [['Le Petit', '30 × 40 cm', '2–4 ans', 'Premier oreiller, soutien très souple'], ['Le Moyen', '40 × 60 cm', '5–8 ans', 'Soutien équilibré, le choix des parents'], ['Le Grand', '50 × 70 cm', '9–12 ans', 'Soutien affirmé, presque comme les grands']],
    guideCols: ['Modèle', 'Dimensions', 'Âge', 'Soutien'],
    storyEyebrow: 'La maison',
    storyTitle: 'La toile de Jouy, retissée pour l\u2019enfance',
    storyText: 'Chaque oreiller est coupé, cousu et garni à la main dans nos ateliers. Les matières sont choisies pour durer toutes les années de la chambre d\u2019enfant — et se laver, souvent.',
    storyCta: 'Découvrir la maison',
    addToCart: 'Ajouter au panier', qty: 'Quantité', size: 'Dimensions', fabricLabel: 'La matière',
    added: 'Ajouté au panier',
    productReassurance: ['Expédié sous 48 h — livraison offerte dès 80 €', '30 nuits d’essai, retours offerts', 'Coton bio certifié OEKO-TEX Standard 100'],
    maison: {
      eyebrow: 'La maison',
      title: 'Une maison française, née d’une chambre d’enfant',
      intro: 'Les Petits Moutons est née d’un constat simple : il n’existait pas de bel oreiller pour enfants. Trop mous, trop synthétiques, trop criards. Nous avons voulu un objet juste — sain, durable, et beau dans la chambre.',
      blocks: [
        ['La toile « Bergerie »', 'Notre toile de Jouy est dessinée à la main puis tissée en France. Bergers, moutons et clochers — une scène du XVIIIᵉ revisitée pour l’enfance.'],
        ['Les ateliers', 'Chaque oreiller est coupé, cousu et garni à la main. Les fanions de coton sont posés un à un, comme une signature.'],
        ['La promesse', 'Des matières certifiées, un soutien pensé par âge, et un objet qui traverse toutes les années de la chambre d’enfant.'],
      ],
      quote: '« Un bel objet pour de belles nuits — rien de plus, rien de moins. »',
    },
    guideSommeil: {
      eyebrow: 'Le guide du sommeil',
      title: 'Bien dormir, ça s’apprend doucement',
      intro: 'Quelques repères simples pour accompagner le sommeil de votre enfant — sans dogme, sans angoisse.',
      articles: [
        ['À quel âge le premier oreiller ?', 'Avant 2 ans, pas d’oreiller — c’est la recommandation pédiatrique. Vers 2–3 ans, au passage au grand lit, un oreiller bas et souple comme Le Petit accompagne la transition.'],
        ['Choisir la bonne hauteur', 'Un bon oreiller comble l’espace entre la nuque et le matelas, sans casser l’alignement du dos. Nos trois tailles suivent la croissance — du soutien très souple au soutien affirmé.'],
        ['Le rituel du soir', 'Une heure régulière, une lumière chaude, une histoire. Les enfants dorment mieux dans la répétition — et dans une chambre qu’ils aiment.'],
        ['L’entretien, sans y penser', 'Housse lavée à 30 °C une fois par mois, garnissage aéré à chaque changement de draps. C’est tout.'],
      ],
      cta: 'Découvrir les trois tailles',
    },
    back: 'Retour aux oreillers',
    tabs: ['Description', 'Entretien', 'Livraison'],
    care: 'Housse déhoussable, lavable en machine à 30 °C. Séchage à l\u2019air libre — le garnissage retrouve son gonflant en quelques heures.',
    shipping: 'Expédition sous 48 h depuis nos ateliers. Livraison offerte dès 80 €, retours offerts pendant 30 jours.',
    review: '« Le Moyen a remplacé trois oreillers achetés en grande surface. On aurait dû commencer par là. » — Claire, maman d\u2019Anna, 6 ans',
    cartEmpty: 'Votre panier est vide, pour l\u2019instant.',
    continueShopping: 'Poursuivre la visite', checkout: 'Passer commande',
    provisional: 'visuel provisoire',
    footerBaseline: 'Oreillers pour enfants, façonnés en France.',
    footerCols: [['La boutique', ['Les oreillers', 'Cartes cadeaux']], ['L\u2019aide', ['Livraison & retours', 'Entretien', 'Nous écrire']], ['La maison', ['Notre histoire', 'Nos ateliers', 'Presse']]],
    legal: '© 2026 Les Petits Moutons — façonné avec soin en France',
  },
  en: {
    nav: ['The pillows', 'The house', 'The sleep guide'],
    cartLabel: 'Your bag', langOther: 'FR',
    reassurance: ['Toile de Jouy woven in France', 'OEKO-TEX certified organic cotton', 'Hand-finished', '30-night trial · free returns'],
    heroEyebrow: 'French maison · since 2026',
    heroTitle: 'Beautiful nights, starting tonight',
    heroSub: 'Three pillows, three ages. Toile de Jouy, organic cotton and tender velvet — made in our French workshops.',
    heroCta: 'Discover the pillows', heroCta2: 'Size guide',
    collTitle: 'Three sizes, one softness',
    collSub: 'A pillow designed for every age, from first naps to big nights.',
    lifestyleEyebrow: 'In their bedrooms',
    lifestyleTitle: 'Designed to be the prettiest thing on the bed',
    lifestyleText: 'Our “Bergerie” print revisits 18th-century toile de Jouy — shepherds, sheep and steeples — in a gentle hand that soothes the evenings.',
    guideTitle: 'Which size for your child?',
    guideRows: [['The Small', '30 × 40 cm', '2–4 years', 'First pillow, very supple support'], ['The Medium', '40 × 60 cm', '5–8 years', 'Balanced support, the parents\u2019 choice'], ['The Large', '50 × 70 cm', '9–12 years', 'Firmer support, almost grown-up']],
    guideCols: ['Model', 'Dimensions', 'Age', 'Support'],
    storyEyebrow: 'The house',
    storyTitle: 'Toile de Jouy, rewoven for childhood',
    storyText: 'Every pillow is cut, sewn and filled by hand in our workshops. Materials are chosen to last all the years of the children\u2019s bedroom — and to be washed, often.',
    storyCta: 'Discover the house',
    addToCart: 'Add to bag', qty: 'Quantity', size: 'Dimensions', fabricLabel: 'The fabric',
    added: 'Added to your bag',
    productReassurance: ['Ships within 48 h — free delivery over €80', '30-night trial, free returns', 'OEKO-TEX Standard 100 certified organic cotton'],
    maison: {
      eyebrow: 'The house',
      title: 'A French maison, born in a child’s bedroom',
      intro: 'Les Petits Moutons was born of a simple observation: there was no beautiful pillow for children. Too soft, too synthetic, too loud. We wanted a just object — healthy, durable, and beautiful in the room.',
      blocks: [
        ['The “Bergerie” toile', 'Our toile de Jouy is drawn by hand, then woven in France. Shepherds, sheep and steeples — an 18th-century scene revisited for childhood.'],
        ['The workshops', 'Every pillow is cut, sewn and filled by hand. The little cotton flags are set one by one, like a signature.'],
        ['The promise', 'Certified materials, age-specific support, and an object made to last all the years of the children’s bedroom.'],
      ],
      quote: '“A beautiful object for beautiful nights — nothing more, nothing less.”',
    },
    guideSommeil: {
      eyebrow: 'The sleep guide',
      title: 'Sleeping well is learned gently',
      intro: 'A few simple landmarks to accompany your child’s sleep — no dogma, no anxiety.',
      articles: [
        ['At what age, the first pillow?', 'Before age 2, no pillow — that is the paediatric recommendation. Around 2–3, with the move to a big bed, a low and supple pillow like The Small eases the transition.'],
        ['Choosing the right height', 'A good pillow fills the space between neck and mattress without breaking the alignment of the back. Our three sizes follow growth — from very supple to firmer support.'],
        ['The evening ritual', 'A regular hour, a warm light, a story. Children sleep better in repetition — and in a room they love.'],
        ['Care, without thinking about it', 'Cover washed at 30 °C once a month, filling aired at every change of sheets. That’s all.'],
      ],
      cta: 'Discover the three sizes',
    },
    back: 'Back to the pillows',
    tabs: ['Description', 'Care', 'Delivery'],
    care: 'Removable cover, machine-washable at 30 °C. Air-dry — the filling regains its loft within hours.',
    shipping: 'Ships within 48 h from our workshops. Free delivery over €80, free returns for 30 days.',
    review: '“The Medium replaced three supermarket pillows. We should have started here.” — Claire, mother of Anna, 6',
    cartEmpty: 'Your bag is empty, for now.',
    continueShopping: 'Keep browsing', checkout: 'Checkout',
    provisional: 'provisional visual',
    footerBaseline: 'Children\u2019s pillows, made in France.',
    footerCols: [['The shop', ['The pillows', 'Gift cards']], ['Help', ['Delivery & returns', 'Care', 'Write to us']], ['The house', ['Our story', 'Our workshops', 'Press']]],
    legal: '© 2026 Les Petits Moutons — made with care in France',
  },
};
